name: Push-to-Rakbook

on: [push, workflow_dispatch]
jobs:
  push-to-rakbok:
    runs-on: ubuntu-latest
    steps:
    - name: Run push mirror script
      env:
        INPUT_SRC_REPO: git@github.com:Rakbook/rakbook.git
        INPUT_PRIVATE_KEY : ${{ secrets.RAKBOOK_SSH_KEY }}
        INPUT_DST_REPO: git@rakbook.pl:rakbook
      run: |
        mkdir .ssh
        echo "adding keys"
        echo "${INPUT_PRIVATE_KEY}" > .ssh/key
        chmod 0600 .ssh/key
        REP=$(mktemp -d repo_XXXXXXXXXXXX)
        echo "cloning repo"
        export GIT_SSH_COMMAND="ssh -i .ssh/key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git clone -v --mirror $INPUT_SRC_REPO $REP
        cd $REP
        echo "pushing repo"
        export GIT_SSH_COMMAND="ssh -i ../.ssh/key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
        git push -v --mirror $INPUT_DST_REPO
        cd ..
        rm -r $REP
